export const portfolioData = {
  personal: {
    name: "Mitkumar Patel",
    title: "Full-Stack Software Developer",
    location: "Windsor, ON, Canada",
    email: "patel77b@uwindsor.ca",
    phone: "+1 437 599 8642",
    github: "https://github.com/mitkumar",
    linkedin: "https://linkedin.com/in/mitkumar",
  },
  
  summary: "Full-Stack Software Developer with hands-on experience in React Native, MERN stack, cloud platforms (Azure), and DevOps pipelines (CI/CD, GitHub Actions). Adept at writing scalable code, automating workflows, and delivering end-to-end solutions. Passionate about agile teamwork, code quality, and solving real-world challenges using modern tech like Docker, RESTful APIs, and Firebase.",
  
  skills: {
    frontend: [
      { name: "React.js / React Native", level: 90 },
      { name: "JavaScript (ES6+)", level: 85 },
      { name: "Redux / State Management", level: 80 },
      { name: "HTML5 / CSS3 / Tailwind", level: 88 },
    ],
    backend: [
      { name: "Node.js / Express.js", level: 85 },
      { name: "MongoDB / MySQL", level: 80 },
      { name: "Microsoft Azure", level: 75 },
      { name: "Docker / CI/CD", level: 70 },
    ],
    languages: ["JavaScript (ES6+)", "Python", "Java", "C++"],
    technologies: [
      { name: "React", icon: "fab fa-react", color: "text-blue-400" },
      { name: "Node.js", icon: "fab fa-node-js", color: "text-green-400" },
      { name: "Python", icon: "fab fa-python", color: "text-yellow-400" },
      { name: "Docker", icon: "fab fa-docker", color: "text-blue-500" },
      { name: "Azure", icon: "fab fa-microsoft", color: "text-orange-400" },
      { name: "MongoDB", icon: "fas fa-database", color: "text-purple-400" },
    ],
  },
  
  experience: [
    {
      id: 1,
      title: "Software Developer Intern",
      company: "Tech Elecon",
      location: "Hybrid (Anand, India)",
      period: "Dec 2023 - Apr 2024",
      type: "primary",
      responsibilities: [
        "Spearheaded development of responsive web applications using React and Node.js",
        "Implemented REST APIs and authentication flows",
        "Worked closely with backend engineers and testers to ensure seamless integration",
        "Integrated MongoDB database for dynamic content management",
      ],
    },
    {
      id: 2,
      title: "Software Developer Intern",
      company: "TatvaSoft",
      location: "Remote (Ahmedabad, India)",
      period: "May 2023 - Jun 2023",
      type: "secondary",
      responsibilities: [
        "Delivered performant single-page apps using React, Redux, and RESTful APIs",
        "Collaborated in agile sprints, performed unit testing, and resolved bugs",
        "Participated in client meetings to capture requirements and deploy feature updates",
        "Ensured app responsiveness and browser compatibility across devices",
      ],
    },
  ],
  
  projects: [
    {
      id: 1,
      title: "Cricket Coaching App",
      description: "Mobile app for video annotation and player-coach interaction with gesture-based tools and real-time sync.",
      technologies: ["React Native", "Expo", "Firebase", "AsyncStorage"],
      category: "Mobile",
      status: "Ongoing",
      github: "https://github.com/mitkumar/cricket-app",
      demo: "#",
      icon: "fas fa-mobile-alt",
      gradient: "from-primary/20 to-secondary/20",
    },
    {
      id: 2,
      title: "Crime Data Analysis Platform",
      description: "Analytics platform using Pandas to process Toronto crime data with algorithmic geospatial heatmaps.",
      technologies: ["Python", "Pandas", "Data Analysis"],
      category: "Analytics",
      status: "Completed",
      github: "https://github.com/mitkumar/crime-prediction",
      icon: "fas fa-chart-line",
      gradient: "from-accent/20 to-warning/20",
    },
    {
      id: 3,
      title: "E-Book Store",
      description: "Complete MERN stack e-commerce platform with authentication, cart functionality, and payment gateway.",
      technologies: ["React", "Node.js", "MongoDB", "Express"],
      category: "E-commerce",
      status: "Completed",
      github: "https://github.com/mitkumar/e-book-store",
      demo: "#",
      icon: "fas fa-shopping-cart",
      gradient: "from-secondary/20 to-primary/20",
    },
    {
      id: 4,
      title: "Expense Tracker",
      description: "Full-stack expense tracking app with real-time sync, analytics, and secure authentication.",
      technologies: ["React", "Redux", "Firebase"],
      category: "Finance",
      status: "Completed",
      github: "https://github.com/mitkumar/expense-tracker",
      icon: "fas fa-chart-pie",
      gradient: "from-accent/20 to-primary/20",
    },
    {
      id: 5,
      title: "MNM Web Store",
      description: "Online store built with PHP and MySQL featuring secure API endpoints and optimized database queries.",
      technologies: ["PHP", "MySQL", "JavaScript"],
      category: "Web Store",
      status: "Completed",
      github: "https://github.com/mitkumar/mnm-web-store",
      icon: "fas fa-store",
      gradient: "from-warning/20 to-secondary/20",
    },
  ],
  
  education: [
    {
      id: 1,
      degree: "Master of Applied Computing",
      institution: "University of Windsor",
      location: "Windsor, ON, Canada",
      period: "Sep 2024 - Present",
      description: "Currently pursuing advanced studies in applied computing with focus on software engineering, cloud technologies, and machine learning applications.",
      icon: "fas fa-graduation-cap",
      color: "primary",
    },
    {
      id: 2,
      degree: "Bachelor of Engineering in Information Technology",
      institution: "G H Patel College of Engineering and Technology",
      location: "Gujarat, India",
      period: "Jun 2020 - Apr 2024",
      gpa: "8.62/10 CGPA",
      description: "Comprehensive study of Information Technology including software development, database management, networking, and project management.",
      icon: "fas fa-user-graduate",
      color: "accent",
    },
  ],
  
  certifications: [
    {
      name: "Spark SQL & DataFrames",
      issuer: "LinkedIn Learning",
      icon: "fas fa-database",
    },
    {
      name: "Microsoft Azure Essentials",
      issuer: "LinkedIn Learning",
      icon: "fab fa-microsoft",
    },
    {
      name: "Intermediate SQL Queries",
      issuer: "LinkedIn Learning",
      icon: "fas fa-search",
    },
    {
      name: "Selenium Essential Training",
      issuer: "LinkedIn Learning",
      icon: "fas fa-robot",
    },
  ],
  
  stats: [
    { label: "Years Experience", value: 2, color: "primary" },
    { label: "Projects Completed", value: 15, color: "accent" },
    { label: "Technologies Mastered", value: 8, color: "secondary" },
  ],
};
